on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - main

name: Format, Test and Deploy

env:
  OTP_VERSION: "23.3"
  ELIXIR_VERSION: "1.13.3"
  HEX_API_KEY: ${{ secrets.HEX_API_KEY }}

jobs:
  deps:
    name: Setup project dependencies
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup environment
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}

      - name: Install dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile

  format:
    name: Check format
    runs-on: ubuntu-latest
    environment: test
    needs:
      - deps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup environment
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}

      - name: Mix Format
        run: mix format --check-formatted

      - name: Run Credo
        run: mix credo --strict

  test:
    name: Executing tests
    runs-on: ubuntu-latest
    environment: test
    needs:
      - deps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup environment
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}

      - name: Run tests
        run: mix test

  deploy:
    name: Deploy library
    runs-on: ubuntu-latest
    environment: prod
    needs:
      - format
      - test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup environment
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}

      - name: Run deployment
        run: mix hex.publish --yes
